Areas/Admin/Controllers/LogicielsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SoftSchool.Models;
using System.IO;

namespace SoftSchool.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrateur")]
    public class LogicielsController : Controller
    {
        private dbsoftschoolEntities1 db = new dbsoftschoolEntities1();

        private string StorageRoot
        {
            get { return Path.Combine(System.Web.HttpContext.Current.Server.MapPath("~/Files/")); } //Path should! always end with '/'
        }

        //
        // GET: /Admin/Logiciels/

        public ViewResult Index()
        {
            return View(db.logiciels.ToList());
        }

        //
        // GET: /Admin/Logiciels/Details/5

        public ViewResult Details(int id)
        {
            logiciels logiciels = db.logiciels.Single(l => l.LogicielID == id);
            return View(logiciels);
        }

        //
        // GET: /Admin/Logiciels/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Admin/Logiciels/Create

        [HttpPost]
        public ActionResult Create(logiciels logiciels)
        {
            if (ModelState.IsValid)
            {
                if (Request.Files.Count == 0)
                    return View(logiciels);
                else
                {
                    HttpPostedFileBase SourceFile = Request.Files["Image"];
                    var inputStream = SourceFile.InputStream;
                    var fullName = StorageRoot + logiciels.Nom + "_" + logiciels.Version + Path.GetExtension(Request.Files["Image"].FileName);
                    logiciels.Image = "Files\\" + logiciels.Nom + "_" + logiciels.Version +  Path.GetExtension(Request.Files["Image"].FileName);
                    using (var fsi = new FileStream(fullName, FileMode.Append, FileAccess.Write))
                    {
                        var buffer = new byte[1024];
                        var l = inputStream.Read(buffer, 0, 1024);
                        while (l > 0)
                        {
                            fsi.Write(buffer, 0, l);
                            l = inputStream.Read(buffer, 0, 1024);
                        }
                        fsi.Flush();
                        fsi.Close();

                        SourceFile = Request.Files["Lien"];
                        inputStream = SourceFile.InputStream;
                        fullName = StorageRoot + "Logs\\" + logiciels.Nom + "_" + logiciels.Version + Path.GetExtension(Request.Files["Lien"].FileName);
                        logiciels.Lien = "Files\\Logs\\" + logiciels.Nom + "_" + logiciels.Version +  Path.GetExtension(Request.Files["Lien"].FileName);
                        using (var fsl = new FileStream(fullName, FileMode.Append, FileAccess.Write))
                        {
                            buffer = new byte[1024];
                            l = inputStream.Read(buffer, 0, 1024);
                            while (l > 0)
                            {
                                fsl.Write(buffer, 0, l);
                                l = inputStream.Read(buffer, 0, 1024);
                            }
                            fsl.Flush();
                            fsl.Close();
                        }

                        db.logiciels.AddObject(logiciels);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
            }
            return View(logiciels);
        }
        
        //
        // GET: /Admin/Logiciels/Edit/5
 
        public ActionResult Edit(int id)
        {
            logiciels logiciels = db.logiciels.Single(l => l.LogicielID == id);
            return View(logiciels);
        }

        //
        // POST: /Admin/Logiciels/Edit/5

        [HttpPost]
        public ActionResult Edit(logiciels logiciels)
        {
            if (ModelState.IsValid)
            {
                db.logiciels.Attach(logiciels);
                db.ObjectStateManager.ChangeObjectState(logiciels, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(logiciels);
        }

        //
        // GET: /Admin/Logiciels/Delete/5
 
        public ActionResult Delete(int id)
        {
            logiciels logiciels = db.logiciels.Single(l => l.LogicielID == id);
            return View(logiciels);
        }

        //
        // POST: /Admin/Logiciels/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            logiciels logiciels = db.logiciels.Single(l => l.LogicielID == id);
            db.logiciels.DeleteObject(logiciels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/Logiciels/Create.cshtml
@model SoftSchool.Models.logiciels


@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm("Create", "Logiciels", FormMethod.Post, new { enctype = "multipart/form-data" })){
    @Html.ValidationSummary(true)
    <table border="0" cellpadding="3" cellspacing="2">
    <tr><td width="100" valign="top" align="right">
        <div class="editor-label">
            @Html.LabelFor(model => model.Nom)
        </div>
        </td><td>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nom)
            @Html.ValidationMessageFor(model => model.Nom)
        </div>
        </td></tr><tr><td>
        <div class="editor-label">
            @Html.LabelFor(model => model.Version)
        </div>
        </td><td>
        <div class="editor-field">
            @Html.EditorFor(model => model.Version)
            @Html.ValidationMessageFor(model => model.Version)
        </div>
        </td></tr><tr><td>
        </td><td>
        
        </td></tr><tr><td>
        <div class="editor-label">
            @Html.LabelFor(model => model.Descreption)
        </div>
         </td><td>
        <div class="editor-field">
            <textarea  id="Descreption" name="Descreption" rows="12" cols="300"></textarea>
            @Html.ValidationMessageFor(model => model.Descreption)
        </div>
        </td></tr><tr><td>
        <div class="editor-label">
            @Html.LabelFor(model => model.Prix)
        </div>
        </td><td>
        <div class="editor-field">
            @Html.EditorFor(model => model.Prix)
            @Html.ValidationMessageFor(model => model.Prix)
        </div>
        </td></tr><tr><td>
        </td><td>
        <div class="editor-field">
        <span class="btn btn-success fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span>Fichier d'installation</span>
                    <input type="file" class="text-box single-line" id="Lien" name="Lien" />
                </span>
        <!--<input type="file" class="text-box single-line" id="Lien" name="Lien" />-->
            
            @Html.ValidationMessageFor(model => model.Lien)
        </div>
        <div class="editor-field">
        <span class="btn btn-success fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span>Logo</span>
                    <input type="file" class="text-box single-line" id="Image" name="Image" />
                </span>
        <!--<input type="file" class="btn btn-success fileinput-button" id="Image" name="Image" />-->
           
            @Html.ValidationMessageFor(model => model.Image)
        </div>
        </td></tr><tr><td>
        </td><td>
        <button type="submit" class="btn btn-primary start">
                    <i class="icon-upload icon-white"></i>
                    <span>Sauvgarder</span>
                </button>
                <a href="/Admin/Logiciels" class="btn btn-warning cancel">Retour</a>

            <!--<input type="submit" value="Create" class="btn btn-primary start"/>-->
    </td></tr>
        </table>
}



Areas/Admin/Views/Logiciels/Delete.cshtml
@model SoftSchool.Models.logiciels

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Logiciels</legend>

    <div class="display-label">Nom</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nom)
    </div>

    <div class="display-label">Version</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Version)
    </div>

    <div class="display-label">Image</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Image)
    </div>

    <div class="display-label">Descreption</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Descreption)
    </div>

    <div class="display-label">Prix</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Prix)
    </div>

    <div class="display-label">Lien</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Lien)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
    <button type="submit" class="btn btn-danger delete">
                    <i class="icon-upload icon-white"></i>
                    <span>Supprimer</span>
                </button>
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Areas/Admin/Views/Logiciels/Details.cshtml
@model SoftSchool.Models.logiciels

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2></h2>

<fieldset>
    <legend> @Html.DisplayFor(model => model.Nom)  @Html.DisplayFor(model => model.Version)</legend>
    <div class="display-field">
    <img src="@Url.Content(@"~\\"+Model.Image)" />
    </div>
    
    <div class="display-label">Descreption</div>
    <div class="display-field">
        @{
            HtmlString str = new HtmlString(Model.Descreption.Replace("\n","<br />"));
        }
        @str
    </div>

    <div class="display-label">Prix</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Prix)
    </div>
    <br />
    <a href="@Url.Content("~\\" + Html.DisplayFor(model => model.Lien))" class="btn btn-primary start">Télécharger</a>
    <a href="/Admin/Logiciels/Edit/@Model.LogicielID" class="btn btn-primary start">Modifier</a> 
    <a href="/Admin/Logiciels" class="btn btn-warning cancel">Retour</a>
</fieldset>
<p>
</p>

Areas/Admin/Views/Logiciels/Edit.cshtml
@model SoftSchool.Models.logiciels

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <table border="0" cellpadding="3" cellspacing="2">
    <tr><td width="100" valign="top" align="right">
        @Html.HiddenFor(model => model.LogicielID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Nom)
        </div>
        </td><td>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nom)
            @Html.ValidationMessageFor(model => model.Nom)
        </div>
        </td></tr><tr><td>
        <div class="editor-label" valign="top" align="right">
            @Html.LabelFor(model => model.Version)
        </div>
        </td><td>
        <div class="editor-field">
            @Html.EditorFor(model => model.Version)
            @Html.ValidationMessageFor(model => model.Version)
        </div>
        </td></tr><tr><td>
        </td><td>
        
        </td></tr><tr><td valign="top" align="right">
        <div class="editor-label">
            @Html.LabelFor(model => model.Descreption)
        </div>
        </td><td>
        <div class="editor-field">
        <textarea  id="Descreption" name="Descreption" rows="12" cols="130">@Model.Descreption</textarea>
            
            @Html.ValidationMessageFor(model => model.Descreption)
        </div>
        </td></tr><tr><td valign="top" align="right">
        <div class="editor-label">
            @Html.LabelFor(model => model.Prix)
        </div>
        </td><td>
        <div class="editor-field">
            @Html.EditorFor(model => model.Prix)
            @Html.ValidationMessageFor(model => model.Prix)
        </div>
        </td></tr><tr><td>
        </td><td>
        <div class="editor-field">
        <span class="btn btn-success fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span>Fichier d'installation</span>
                    <input type="file" class="text-box single-line" id="NLien" name="NLien" />
                    <input type="hidden" value="@Model.Lien" name="Lien" id="Lien" />
                </span>
           
            @Html.ValidationMessageFor(model => model.Lien)
        </div>
        <div class="editor-field">
        <span class="btn btn-success fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span>Logo</span>
                    <input type="file" class="text-box single-line" id="NImage" name="NImage" value="@Model.Image"/>
                    <input type="hidden" value="@Model.Image" name="Image" id="Image" />
                </span>
            
            @Html.ValidationMessageFor(model => model.Image)
        </div>
        </td></tr><tr><td>
        </td><td>
        <br />
        <p>
            <button type="submit" class="btn btn-primary start">
                    <i class="icon-upload icon-white"></i>
                    <span>Sauvgarder</span>
                </button>
            <a href="/Admin/Logiciels" class="btn btn-warning cancel">Retour</a>
        </p>
        </td></tr>
        </table>
}


Areas/Admin/Views/Logiciels/Index.cshtml
@model IEnumerable<SoftSchool.Models.logiciels>

@{
    ViewBag.Title = "Logiciels";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<fieldset>

<p>

<a href="/Admin/Logiciels/Create" class="btn btn-primary start">Ajouter Logiciel</a>
</p>
<table id="customersadmin">
    <tr>
    <th width="70"></th>
        <th width="100">
            Libelle
        </th>
        
        
        <th width="30%">
            Descreption
        </th>
        <th width="50">
            Prix
        </th>
        
        <th width="240"></th>
    </tr>

@foreach (var item in Model) {
    <tr>
    <td align="center">
        <img src="@Url.Content("~\\"+item.Image)" alt="@item.Nom" width="60" height="60"/>
        
        </td>
        <td valign="top" align="center">
            @Html.DisplayFor(modelItem => item.Nom)
        </td>
        
        
        <td valign="top" align="center">
           @{
    HtmlString str = new HtmlString(item.Descreption.Replace("\n", "<br />"));
        }
        @str
        </td>
        <td valign="top" align="center">
            @Html.DisplayFor(modelItem => item.Prix)
        </td>
        <td align="center">
        <a href="@Url.Content("~\\" + item.Lien)" class="btn btn-primary start">Télécharger</a>
            <a href="/Admin/Logiciels/Edit/@item.LogicielID" class="btn btn-success fileinput-button">Modifier</a>
            <a href="/Admin/Logiciels/Details/@item.LogicielID" class="btn btn-success fileinput-button">Details</a> 
            <a href="/Admin/Logiciels/Delete/@item.LogicielID" class="btn btn-danger delete">Supprimer</a>        </td>
    </tr>
}

</table>
</fieldset>