Areas/Admin/Controllers/AdminMailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using SoftSchool.Models;
using System.Data;
using System.Data.Entity;
using MySql.Data.MySqlClient;
using MySql.Web;
using MySql.Web.Security;
using System.IO;
using Mvc.Mailer;
using SoftSchool.Mailers;

namespace SoftSchool.Areas.Admin.Controllers
{
    public class AdminMailController : Controller
    {
        private string StorageRoot
        {
            get { return Path.Combine(System.Web.HttpContext.Current.Server.MapPath("~/Files/")); } //Path should! always end with '/'
        }

        private dbsoftschoolEntities1 db = new dbsoftschoolEntities1();
        //
        // GET: /Admin/mail/

        public ActionResult Index()
        {
            return RedirectToAction("InBox");
        }

        #region Inbox
        public ActionResult InBox(int page=1)
        {
            var model = db.outbox.ToList();
            model = pagination(model, page);
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var model = db.outbox.SingleOrDefault(o => o.id == id);
            return View(model);        
        }

        public ActionResult Repondre(int id)
        {
            var model = db.outbox.SingleOrDefault(o => o.id == id);
            ViewBag.contact = model.id;
            return View(new inbox());
        }

        [HttpPost]
        public ActionResult Repondre(inbox model)
        {
            if (model.subject!=null && model.objet!=null)
            {
                if(model.file!=null)
                {
                    HttpPostedFileBase SourceFile = Request.Files["file"];
                    var inputStream = SourceFile.InputStream;
                    var fullName = StorageRoot + "Joint\\" + User.Identity.Name + "_" + DateTime.Now.ToString("yy_MM_dd_hh_mm_ss") + "_" + Path.GetFileName(Request.Files["file"].FileName).Replace(" ", "_");
                    model.file = User.Identity.Name + "_" + DateTime.Now.ToString("yy_MM_dd_hh_mm_ss") + "_" + Path.GetFileName(Request.Files["file"].FileName).Replace(" ", "_");
                    using (var fsi = new FileStream(fullName, FileMode.Append, FileAccess.Write))
                    {
                        var buffer = new byte[1024];
                        var l = inputStream.Read(buffer, 0, 1024);
                        while (l > 0)
                        {
                            fsi.Write(buffer, 0, l);
                            l = inputStream.Read(buffer, 0, 1024);
                        }
                        fsi.Flush();
                        fsi.Close();
                    }
                }
                model.UserId = getuser().aspnet_user;
                outbox ot = db.outbox.SingleOrDefault(o => o.id == model.Contact);
                model.Contact = ot.UserId;
                model.date_envoie = DateTime.Now;
                db.inbox.AddObject(model);

                ot.contact = model.UserId;
                db.ObjectStateManager.ChangeObjectState(ot, EntityState.Modified);

                db.SaveChanges();
                
                ViewBag.contact = model.UserId;
                return RedirectToAction("InBox");
            }
            else
            {
                return View(model);
            }
        }

        private List<SoftSchool.Models.outbox> pagination(List<SoftSchool.Models.outbox> model, int page)
        {
            int div = 10;
            ViewBag.current = page;
            int count = model.Count();
            int nbp = count / div;
            if ((count % div) != 0)
                nbp++;
            ViewBag.NbrPage = nbp;
            List<SoftSchool.Models.outbox> lyc = new List<outbox>();
            if (count != 0)
            {
                if (page < nbp)
                {
                    lyc = model.GetRange(((page - 1) * div), div);
                }
                else
                {
                    div = count - ((page - 1) * div);
                    lyc = model.GetRange(((page - 1) * div), div);
                }
            }
            return lyc;
        }


        #endregion
        
        #region Outox

        public ActionResult OutBox(int page = 1)
        {
            var model = db.inbox.ToList();
            model = pagination(model, page);
            return View(model);
        }

        public ActionResult DetailsOutBox(int id)
        {
            var model = db.inbox.SingleOrDefault(o => o.ID == id);
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            var model = db.inbox.SingleOrDefault(i => i.ID == id);
            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            inbox activation = db.inbox.Single(l => l.ID == id);
            db.inbox.DeleteObject(activation);
            db.SaveChanges();
            return RedirectToAction("OutBox");
        }

        public ActionResult Nouveau()
        {
            inbox model = new inbox();
            ViewBag.Dres = db.dres.ToList();
            return View(model);
        }

        [HttpPost]
        public ActionResult Nouveau(inbox model)
        {
            model.UserId = getuser().aspnet_user;

            if (model.file != null)
            {
                HttpPostedFileBase SourceFile = Request.Files["file"];
                var inputStream = SourceFile.InputStream;
                var fullName = StorageRoot + "Joint\\" + User.Identity.Name + "_" + DateTime.Now.ToString("yy_MM_dd_hh_mm_ss") + "_" + Path.GetFileName(Request.Files["file"].FileName).Replace(" ", "_");
                model.file = User.Identity.Name + "_" + DateTime.Now.ToString("yy_MM_dd_hh_mm_ss") + "_" + Path.GetFileName(Request.Files["file"].FileName).Replace(" ", "_");
                using (var fsi = new FileStream(fullName, FileMode.Append, FileAccess.Write))
                {
                    var buffer = new byte[1024];
                    var l = inputStream.Read(buffer, 0, 1024);
                    while (l > 0)
                    {
                        fsi.Write(buffer, 0, l);
                        l = inputStream.Read(buffer, 0, 1024);
                    }
                    fsi.Flush();
                    fsi.Close();
                }
            }
            model.date_envoie = DateTime.Now;
            db.inbox.AddObject(model);
            db.SaveChanges();
            ViewBag.Dres = db.dres.ToList();
            my_aspnet_membership mem= db.my_aspnet_membership.SingleOrDefault(x => x.userId == model.Contact);
            new WelcomeMailer().Welcome(mem, model.subject, model.objet).Send();
            return RedirectToAction("OutBox");
        }

        private List<SoftSchool.Models.inbox> pagination(List<SoftSchool.Models.inbox> model, int page)
        {
            int div = 10;
            ViewBag.current = page;
            int count = model.Count();
            int nbp = count / div;
            if ((count % div) != 0)
                nbp++;
            ViewBag.NbrPage = nbp;
            List<SoftSchool.Models.inbox> lyc = new List<inbox>();
            if (count != 0)
            {
                if (page < nbp)
                {
                    lyc = model.GetRange(((page - 1) * div), div);
                }
                else
                {
                    div = count - ((page - 1) * div);
                    lyc = model.GetRange(((page - 1) * div), div);
                }
            }
            return lyc;
        }


       

        #endregion

       

        private utilisateur getuser()
        {
            my_aspnet_users us = db.my_aspnet_users.SingleOrDefault(u => u.name == User.Identity.Name);
            if (us != null)
            {
                return db.utilisateur.SingleOrDefault(u => u.aspnet_user == us.id);
            }
            else
                return null;
        }
    }
}

Areas/Admin/Views/AdminMail/Delete.cshtml
@model SoftSchool.Models.inbox

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    SoftSchool.Models.Metier met = new SoftSchool.Models.Metier();
}
<br />
<h5><b>Êtes-vous sûr de vouloir supprimer?</b></h5>
<br />
@using (Html.BeginForm()) {
    <p>
    <button type="submit" class="btn btn-danger delete" value="Delete" >
                    <i class="icon-upload icon-white"></i>
                    <span>Delete</span>
                </button>
        <a href="/Admin/AdminMail/OutBox" class="btn btn-warning cancel">Retour</a>
      <!--  <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "OutBox")-->
    </p>
}

<fieldset>

    <div class="display-label">Contact</div>
    <div class="display-field">
        @met.getContactByLycéee(Model.Contact.Value) ==> @met.getContactByNom(Model.Contact.Value)
        <br />
        @Html.DisplayFor(model => model.date_envoie)
    </div>

    <div class="display-label">suject</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.subject)
    </div>

    <div class="display-label">0bjet</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.objet)
    </div>

   @if(Model.file!=null){
        <div class="display-label">Pièce Jointe</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.file)
        </div>
    }
    
</fieldset>
<br /><br />

Areas/Admin/Views/AdminMail/Details.cshtml
@model SoftSchool.Models.outbox

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    SoftSchool.Models.Metier met = new SoftSchool.Models.Metier();
}
<br />
<div class="entmail">
<div class="fleft">
        <h6> <b>@met.getContactByLycéee(Model.UserId)</b> <b1>< @met.getContactByNom(Model.UserId) ></b1></h6>
       
        <br />
        <h7><b1>@Model.subject</b1></h7>  @if (Model.file != null)
    {
    <a href="@Url.Content("~/Files/Joint/"+@Model.file)" class="btn btn-info upload"><img src="@Url.Content("~/Content/images/piece-jointe.png")" alt="@Model.file"/> Télécharger Pièce Jointe</a>
    }
        
    &nbsp
</div>
<div class="fright">
<a href="/Admin/AdminMail/Repondre/@Model.id" class="btn btn-success upload"><span width="70">Répondre</span> </a><br /><br />
    <a href="/Admin/AdminMail" class="btn btn-info upload"><span width="100">&nbsp Retour&nbsp&nbsp</span></a>
</div>
</div>
<div class="mail">
    <div>
    @if(Model.objet!=null){
        HtmlString str = new HtmlString(Model.objet.Replace("\n", "<br />"));
        <h7> @str</h7>
    }
       
        
    </div>
</div>


Areas/Admin/Views/AdminMail/DetailsOutBox.cshtml
@model SoftSchool.Models.inbox

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    SoftSchool.Models.Metier met = new SoftSchool.Models.Metier();
}
<br />
<div class="entmail">
<div class="fleft">
        <h6> <b>@met.getContactByLycéee(Model.UserId)</b> <b1>< @met.getContactByNom(Model.UserId) ></b1></h6>
       
        <br />
        <h7><b1>@Model.subject</b1></h7>  @if (Model.file != null)
    {
    <a href="@Url.Content("~/Files/Joint/"+@Model.file)" class="btn btn-info upload"><img src="@Url.Content("~/Content/images/piece-jointe.png")" alt="@Model.file"/> Télécharger Pièce Jointe</a>
    }
        
    &nbsp
</div>
<!--
<div class="fright">
<a href="/Admin/AdminMail/Repondre/@Model.ID" class="btn btn-success upload"><span width="70">Répondre</span> </a><br /><br />
    <a href="/Admin/AdminMail" class="btn btn-info upload"><span width="100">&nbsp Retour&nbsp&nbsp</span></a>
</div>-->
</div>
<div class="mail">
    <div>
    @if(Model.objet!=null){
        HtmlString str = new HtmlString(Model.objet.Replace("\n", "<br />"));
        <h7> @str</h7>
    }
       
        
    </div>
</div>

Areas/Admin/Views/AdminMail/InBox.cshtml
@model IEnumerable<SoftSchool.Models.outbox>

@{
    ViewBag.Title = "InBox";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    SoftSchool.Models.Metier met = new SoftSchool.Models.Metier();
}
<h5><b>Boite de Réception</b></h5>
<table id="customersadmin">
    <tr>
        <th width="150">
            Lycée
        </th>
       <th  width="150">
            Contact
        </th>
        <th width="80">
            Date
        </th>
        <th width="170">
            Sujet
        </th>
        <th>
            Objet
        </th>
       <!-- <th>
            Fichier Joint
        </th>
        -->
        <th width="120"></th>
    </tr>

@foreach (var item in Model)
{
     string alt = "";
    if (item.contact == null)
    {
        alt = "alt";
    }
    <tr class="@alt">
        <td >
             @met.getContactByLycéee(item.UserId)
        </td>
         <td>
             @met.getContactByNom(item.UserId)
        </td>
        <td >
            @item.date_envoie.ToShortDateString()
            
        </td>
        <td>
        @if (item.subject != null)
            {
                string sobj = item.subject;
                if (sobj.Length >= 25)
                {
                    sobj = item.subject.Substring(0, 25);
                    sobj += "...";
                }
            @sobj
            }
            @{
       if (item.file != null)
       { 
            <img src="@Url.Content("~/Content/images/piece-jointe.png")" alt="@item.file"/>
       }
             }
        </td>
        <td >
            @if (item.objet != null)
            {
                string obj = item.objet;
                if (obj.Length >= 90)
                {
                    obj = item.objet.Substring(0, 90);
                    obj += "...";
                }
            @obj
            }
        </td>
        <!--
        <td width="30">
            @Html.DisplayFor(modelItem => item.file)
        </td>
        -->
        <td>
            @Html.ActionLink("Details", "Details", new { id = item.id }) |
            @Html.ActionLink("Supprimer", "Delete", new { id = item.id })
        </td>
    </tr>
}

</table>

@{
    if (ViewBag.NbrPage != 1)
    {
        <div class="pagination">
        @for (int i = 1; i <= ViewBag.NbrPage; i++)
        {
            if (i != ViewBag.current)
            {
		        <a href="/Admin/AdminMail/InBox/?page=@i" class="page gradient">@i</a>
            }
            else
            {
                <a class="page active">@i</a>
            }
        }
        </div>
    }
    else
    {
        <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
     <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
     <br />
    <br />
    <br />
    <br />
   }
}

Areas/Admin/Views/AdminMail/Nouveau.cshtml
@model SoftSchool.Models.inbox

@{
    ViewBag.Title = "Nouveau";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Nouveau", "AdminMail", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <!--
    <fieldset>
        <div class="editor-label">
            @Html.LabelFor(model => model.Contact)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Contact)
            @Html.ValidationMessageFor(model => model.Contact)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.subject)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.subject)
            @Html.ValidationMessageFor(model => model.subject)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.objet)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.objet)
            @Html.ValidationMessageFor(model => model.objet)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LogicielID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LogicielID)
            @Html.ValidationMessageFor(model => model.LogicielID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.cle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.cle)
            @Html.ValidationMessageFor(model => model.cle)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Reponse)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Reponse)
            @Html.ValidationMessageFor(model => model.Reponse)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserId)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.file)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.file)
            @Html.ValidationMessageFor(model => model.file)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.date_envoie)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.date_envoie)
            @Html.ValidationMessageFor(model => model.date_envoie)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
    
    -->
    <script type="text/javascript">
        $(document).ready(function () {
            $("#Direction").change(function () {
                var idModel = $(this).val();
                $.getJSON("/Account/GetVilles", { id: idModel },
                    function (carData) {
                        var select = $("#Ville");
                        select.empty();
                        var select1 = $("#IDLycees");
                        select1.empty();
                        select.append($('<option/>', {
                            value: 0,
                            text: "إختر المدينة..."
                        }));
                        $.each(carData, function (index, itemData) {

                            select.append($('<option/>', {
                                value: itemData.Value,
                                text: itemData.Text
                            }));
                        });
                    });
            });
            $("#Ville").change(function () {
                var idColour = $(this).val();
                $.getJSON("/Account/GetLycees", { id: idColour },
                    function (modelData) {
                        var select = $("#IDLycees");
                        select.empty();
                        select.append($('<option/>', {
                            value: 0,
                            text: "إختر المؤسسة..."
                        }));
                        $.each(modelData, function (index, itemData) {

                            select.append($('<option/>', {
                                value: itemData.Value,
                                text: itemData.Text
                            }));
                        });
                    });
                });

                $("#IDLycees").change(function () {
                    var idColour = $(this).val();
                    $.getJSON("/Account/GetUSERS", { id: idColour },
                    function (modelData) {
                        var select = $("#Contact");
                        select.empty();
                        select.append($('<option/>', {
                            value: 0,
                            text: "إختر المستخدم..."
                        }));
                        $.each(modelData, function (index, itemData) {

                            select.append($('<option/>', {
                                value: itemData.Value,
                                text: itemData.Text
                            }));
                        });
                    });
                });
        });

</script>
    
    
     <table>
        <tr>
            <td>
                Direction:
            </td>
            <td>
                <select id="Direction" name="Direction">
        <option value="-1">إختر الممندوبية...</option>
        @{
            foreach(SoftSchool.Models.dres dre in ViewBag.Dres)
            {
                <option value="@dre.DreId">@dre.Nom_Ar</option>
            }
         }
         </select>
            </td>
        </tr>
        <tr>
            <td>
                Ville:
            </td>
            <td>
                 @Html.DropDownList("Ville", new SelectList(Enumerable.Empty<SelectListItem>(), "VilleID", "Nom_Ar"))
            </td>
        </tr>
        <tr>
            <td>
                Lycée:
            </td>
            <td>
                 @Html.DropDownList("IDLycees", new SelectList(Enumerable.Empty<SelectListItem>(), "Code", "Nom"))
            </td>
        </tr>
        <tr>
            <td>
                Contact:
            </td>
            <td>
                 @Html.DropDownList("Contact", new SelectList(Enumerable.Empty<SelectListItem>(), "Contact", "Nom"))
            </td>
        </tr>
        <tr>
            <td>
                Sujet:
            </td>
            <td>
            @{
                string subj="";
            if (Model.subject != null) { subj = Model.subject; }
            }
                <input class="subject" id="subject" name="subject" type="text" value="@subj" />
                @Html.ValidationMessageFor(model => model.subject)
            </td>
        </tr>
        <tr>
            <td>
                Pièce Jointe:
            </td>
            <td>
                <input type="file"  id="file" name="file" />
                @Html.ValidationMessageFor(model => model.file)
            </td>
        </tr>
         <tr>
            <td>
                
            </td>
            <td>
                <textarea cols="100" id="objet" name="objet" rows="15">@if (Model.objet != null)
                                                                       {@Model.objet;
                                                                       }</textarea>                @Html.ValidationMessageFor(model => model.objet)
            </td>
        </tr>
        <tr>
        <td>
    
        </td>
        <td>
            <p>
                <input type="submit" class="btn btn-success fileinput-button" value="Envoyer" />
                <a href="/Admin/AdminMail" >                <input type="button" class="btn btn-info upload" value="Retour" />                </a>            </p>
        </td>
        </tr>
    </table>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Areas/Admin/Views/AdminMail/OutBox.cshtml
@model IEnumerable<SoftSchool.Models.inbox>

@{
    ViewBag.Title = "OutBox";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    SoftSchool.Models.Metier met = new SoftSchool.Models.Metier();
}
<br />
<table><tr>
<td width="200"><h5><b>Boite d'envoie</b></h5></td>
<td><a href="/Admin/AdminMail/Nouveau" class="btn btn-success fileinput-button">Nouveau</a></td>
</tr></table>

<table id="customersadmin">
    <tr>
        <th width="150">
            Contact
        </th>
        <th width="180">
            suject
        </th>
        <th>
            Objet
        </th>
        
        <th width="80">
            date Envoie
        </th>
        <th width="120"></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
        @met.getContactByLycéee(item.Contact.Value)
        </td>
        <td>
            @if (item.subject != null)
            {
                string sobj = item.subject;
                if (sobj.Length >= 25)
                {
                    sobj = item.subject.Substring(0, 25);
                    sobj += "...";
                }
            @sobj
            }
            @{
            if (item.file != null)
            { 
            <img src="@Url.Content("~/Content/images/piece-jointe.png")" alt="@item.file"/>
            }
             }
        </td>
        <td>
        @if (item.objet != null)
        {
            string obj = item.objet;
            if (obj.Length >= 77)
            {
                obj = item.objet.Substring(0, 77);
                obj += "...";
            }
            @obj
        }
        </td>
       
        <td>
       @if(item.date_envoie!=null)
       {
            @item.date_envoie.Value.ToShortDateString();
       }
        </td>
        <td>
            @Html.ActionLink("Details", "DetailsOutBox", new { id = item.ID }) |
            @Html.ActionLink("Supprimer", "Delete", new { id = item.ID })
        </td>
    </tr>
}

</table>


@{
    if (ViewBag.NbrPage != 1)
    {
        <div class="pagination">
        @for (int i = 1; i <= ViewBag.NbrPage; i++)
        {
            if (i != ViewBag.current)
            {
		        <a href="/Admin/AdminMail/OutBox/?page=@i" class="page gradient">@i</a>
            }
            else
            {
                <a class="page active">@i</a>
            }
        }
        </div>
    }
    else
    {
        <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
     <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
     <br />
    <br />
    <br />
    <br />
   }
}

Areas/Admin/Views/AdminMail/Repondre.cshtml
@model SoftSchool.Models.inbox

@{
    ViewBag.Title = "Repondre";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<br />
<br />
@using (Html.BeginForm("Repondre", "AdminMail", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <input data-val="true"  id="Contact" name="Contact" type="hidden" value="@ViewBag.contact" />
   
    
     <table>
        <tr>
            <td>
                Sujet:
            </td>
            <td>
                <input class="subject" id="subject" name="subject" type="text" value="@Model.subject" />
                @Html.ValidationMessageFor(model => model.subject)
            </td>
        </tr>
        <tr>
            <td>
                Pièce Jointe:
            </td>
            <td>
                <input type="file"  id="file" name="file" />
                @Html.ValidationMessageFor(model => model.file)
            </td>
        </tr>
         <tr>
            <td>
                
            </td>
            <td>
                <textarea cols="100" id="objet" name="objet" rows="15">@if (Model.objet != null){@Model.objet;}</textarea>                @Html.ValidationMessageFor(model => model.objet)
            </td>
        </tr>
        <tr>
        <td>
    
        </td>
        <td>
            <p>
                <input type="submit" class="btn btn-success fileinput-button" value="Envoyer" />
                <a href="/Admin/AdminMail" >                <input type="button" class="btn btn-info upload" value="Retour" />                </a>            </p>
        </td>
        </tr>
    </table>
    
}